name: Page Insight Reports

on:
  push:
    branches: [rc]
  pull_request:
    branches: [rc]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Running Page Speed Insights
      uses: jakepartusch/psi-action@v1.3
      id: psi
      with:
        url: "https://rc.afetharita.com"
        threshold: 60
        strategy: mobile
        # key: ${{ secrets.APIKEY }} 
        # not sure if this is needed, but it's in the example

